name: Kryptokrona Kotlin SDK Master Pipeline

env:
  KRYPTOKRONA_HTTP_KOVER_XML: ./kryptokrona-http/build/reports/kover/report.xml
  KRYPTOKRONA_CRYPTO_KOVER_XML: ./kryptokrona-crypto/build/reports/kover/report.xml

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Assemble
        run: ./gradlew assemble

      - name: Compile C library
        run: ./gradlew cCompile

      - name: Copy C library
        run: ./gradlew copyCLibrary

      - name: Copy C headers
        run: ./gradlew copyCHeaders

      - name: Upload C library
        uses: actions/upload-artifact@v2
        with:
          name: kryptokrona-crypto
          path: kryptokrona-crypto/build/libs

      - name: Upload C headers
        uses: actions/upload-artifact@v2
        with:
          name: kryptokrona-crypto-headers
          path: kryptokrona-crypto/build/headers

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Download C library
        uses: actions/download-artifact@v2
        with:
          name: kryptokrona-crypto
          path: kryptokrona-crypto/build/libs

      - name: Download C headers
        uses: actions/download-artifact@v2
        with:
          name: kryptokrona-crypto-headers
          path: kryptokrona-crypto/build/headers

      - name: Run Unit Test
        run: ./gradlew test

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: [ assemble ]

    steps:
      - uses: actions/checkout@master

      - name: Generate Kover XML Reports
        run: ./gradlew test koverXmlReport

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.KRYPTOKRONA_HTTP_KOVER_XML }}, {{ env.KRYPTOKRONA_CRYPTO_KOVER_XML }}
          flags: unittests, grid # optional
          layout: horizontal
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
